# Generated by Django 3.0 on 2019-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191211_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanantype',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='makanantype',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='platter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='plattertype',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='plattertype',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
