# Generated by Django 3.0 on 2019-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191211_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
