# Generated by Django 3.0 on 2019-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191211_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='saladtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
